Execution Result Buttons
hpi-swa-lab/babylonian-programming-smalltalk pull request #13
Opened 2020-12-01 13:26 UTC by JoeAtHPI

Each example gets a button which display its return value when executed in the corresponding method
![image](https://user-images.githubusercontent.com/33000454/100746522-1a7d2780-33e1-11eb-8422-ec299b186aa2.png)

2020-12-01 17:44 UTC, codeZeilen requested changes

2020-12-01 17:44 UTC, codeZeilen commented on packages/Babylonian-Core.package/BPMethodExample.class/instance/execute.st
> +	|executionResult|
The code for recording the execution result should actually be in BlockClosure>>#bpTraceWith: tracer and should make use of `BPActiveTracer value` to ensure that the trace is constructed correctly.

2020-12-01 17:44 UTC, codeZeilen commented on packages/Babylonian-Core.package/BPMethodExample.class/instance/execute.st
> +	|executionResult|
Which is the code used in bpTraceExecutionResult: :)

2020-12-01 17:44 UTC, codeZeilen commented on packages/Babylonian-Tests.package/BPTracingTest.class/instance/testTracingOfExecutionResult.st
> +	self assert: (result executionResult) equals: 4
Too many parentheses :)

2020-12-01 17:46 UTC, codeZeilen requested changes
comments are inline

2020-12-01 17:47 UTC, codeZeilen commented on packages/Babylonian-Core.package/BPMethodExample.class/instance/execute.st
> +								on: Error
This causes the test failures as it masks the errors we actually want to record. See BlockClosure>>#bpTraceWith: for how this is done. When the code moves there you actually will not need the exception handling in this line anymore.

2020-12-03 21:12 UTC, JoeAtHPI commented
@codeZeilen

2020-12-03 21:14 UTC, JoeAtHPI commented
what do you mean with comments are inline? i just corrected a typo in the existing one

2020-12-04 12:35 UTC, merged