Consistent Theme Styling for Annotations + auto update on change
hpi-swa-lab/babylonian-programming-smalltalk pull request #150
Opened 2023-07-02 21:19 UTC by JoeAtHPI

Currently, many colors are hardcoded throughout the code. This leads to hardly readable, or unreadable text depending on the theme, e.g. the grey of the buttons in a dark theme
![Screenshot 2023-05-16 193223](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/33000454/f48dd2df-5665-4a15-9d9e-3eb93894e969)
or backgrounds were inconsistent
![Screenshot 2023-05-31 140808](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/33000454/241ef38e-21cb-4af5-b13a-d0028e779540)

With this MR, colors adjust themselves to the theme and change automatically when a new change is applied.
Many `applyUserInterfaceTheme` and UI constants were added. As the values morph for Probes was different with each class, fullfilling the same purpose, they were extracted into their own classes. `BPBrowser` now invalidates itself when a theme changed. This is because in the scenario
1) Browser display method `a` with probes
2) User switches to method `b`
3) User switches theme
4) User goes back to `a`
the probes in `a` would still have the old theme as they were not rendered before.

Below are two example themes.

![Screenshot 2023-06-01 164550](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/33000454/40776aa5-4550-4b8f-a085-609d196f891b)
![Screenshot 2023-06-01 164915](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/33000454/1e30251c-a9ee-4f0a-942b-036a40cf9739)
![Screenshot 2023-05-31 200753](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/33000454/66710ed5-e31b-43c5-b60d-e2dc76c3d1e4)

2023-07-03 13:53 UTC, ekrebs5 requested changes
![grafik](https://github.com/hpi-swa-lab/babylonian-programming-smalltalk/assets/12158488/771f3eab-614e-4bdd-b233-d4aca72f3c7c)

Looks good in general, just have a few inputs:
- it tries to readd the printbugger package; this is the probelog now
- see comment that one color could be extracted to its own function
- as seen in the screenshots, dark themes such as Monokai (dark) retain a light color for some Babylonian Morphs if the browser is open during the change; can this be fixed or will a browser reopen be neccessary here?

2023-07-03 13:53 UTC, ekrebs5 commented on .smalltalk.ston
> +      #categories : [ 'Babylonian-Core', 'Babylonian-UI', 'Babylonian-Compiler', 'Babylonian-Printbugger' ]
This should stay ProbeLog

2023-07-03 13:53 UTC, ekrebs5 commented on packages/Babylonian-UI.package/BPMethodExampleMorph.class/instance/addArgumentScriptMorphs.st
> +			color: self class textColor;
This is in this method and #addReceiverConstructorMorph; maybe extract into its own method

2023-07-04 11:15 UTC, JoeAtHPI commented
@ekrebs5 did you mean the printbugger in the .ston? or elsewhere?

2023-07-04 11:20 UTC, ekrebs5 approved these changes

2023-07-04 12:23 UTC, merged